### ISSUE TITLE
RNG schema text encoding could be changed from iso-8859-1 to utf-8

### ISSUE THREAD

**Issue by fordmadox** [SAA-SDT/EAD2002#1]
Note:  the eas-validator tool is currently pointed to the LoC version of the EAD2002 RNG schema due to text encoding issues with the file that's hosted on GitHub.  Updating both to utf-8 should do the trick, but not entirely necessary unless the LoC version is taken offline.

**Comment by kerstarno** [comment]
Note for @fordmadox: I will leave this with you and the Schema team to monitor with regard to continuing to have the LoC version of the EAD2002 RNG schema available online as a fall-back option.

**Comment by fordmadox** [comment]
Note:  issue 3 has also been merged with his branch: https://github.com/SAA-SDT/EAD2002/pull/4

**Comment by fordmadox** [comment]
Closing this issue, which has been fixed with https://github.com/SAA-SDT/EAD2002/commit/6d1881a11168014bb01c97f5e92f9bef761bceba
