### ISSUE TITLE
Script code values in the schema are not up to date anymore

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/EAD2002#2]
The following was posted to the EAS Section's mailing list by Rebecca Romanchuk, Team Lead/Archivist III at Texas State Library and Archives Commission, Austin, TX:

I've found that not all script codes listed in the ISO 15924 (http://www.unicode.org/iso15924/iso15924-codes.html) are available in the drop-down menu for the script code attribute in EAD 2002 Schema. For example, "Jpan", though there are many others not included in the menu list. Is this a known limitation for EAD 2002 Schema?

My institution is part of an EAD consortium (still using EAD 2002 Schema) that is contemplating making script code a required attribute for collection-level language element. If complying with this requirement won't always be possible because the script code menu isn't complete for ISO 15924, I want to bring this up for consideration to make script code only preferred or optional.

Thanks in advance for any insights!

**Comment by kerstarno** [comment]
EAD team to consider this in the wider context of updates to all ISO standards that have code lists included in the EAD 2002 schema. Might be a question of a minor update as part of the current revision cycle. To be discussed during the next meeting on 9 November.

**Comment by kerstarno** [comment]
EAD team discussed this topic during their November 2020 meeting. While the team acknowledged the issue with regard to outdated value lists for the various ISO codes used in EAD2002, the general decision has been taken, that TS-EAS will not make updates to previous versions of the schemas for the standards it manages. Once a new version of a standard is released, only the latest version will see patch and minor releases.

However, it also has been decided that this issue will be referred to the Schema team of TS-EAS to investigate alternative solutions to the issue raised (note for @fordmadox).

**Comment by fordmadox** [comment]
Closing this issue.  See https://github.com/SAA-SDT/EAD2002/tree/release/final, which will include a separate set of changes to address the final update.
